install: 
	mkdir -p $(DESTDIR)/usr/share/cockpit/cockpit-iptv
	cp -r ./cockpit-iptv/* $(DESTDIR)/usr/share/cockpit/cockpit-iptv
	mkdir -p $(DESTDIR)/usr/share/metainfo/
	cp org.cockpit-project.cockpit-iptv.metainfo.xml $(DESTDIR)/usr/share/metainfo/
